require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  # Enable new cops by default
  NewCops: enable
  
  # Exclude directories and files that shouldn't be linted
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'db/migrate/**/*'  # Migrations have their own style
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'app/views/**/*'  # ERB templates have different conventions
    - 'config/environments/*'
    - 'node_modules/**/*'
    - 'config/initializers/**/*'  # Initializers may have different style
    - 'coverage/**/*'
    - 'spec/support/**/*'  # Spec support files may have different conventions
  
  # Display cop names in offense messages
  DisplayCopNames: true
  
  # Display style guide URLs in offense messages
  DisplayStyleGuide: true
  
  # Use the default target Ruby version
  TargetRubyVersion: 3.2

# Layout cops
Layout/LineLength:
  Max: 120
  # Allow long lines in certain contexts
  Exclude:
    - 'spec/**/*'  # Spec files may have longer lines
  AllowedPatterns:
    - '\s*#'  # Allow long comment lines

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/FirstArgumentIndentation:
  EnforcedStyle: consistent

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

# Style cops
Style/FrozenStringLiteralComment:
  Description: >-
    Add the frozen_string_literal comment to the top of files
    to help transition from Ruby 2.3.0 to Ruby 3.0.
    While this is a Ruby best practice, it can cause issues with certain gems
    and is optional for Rails 6.1+ applications.
  Enabled: false
  Exclude:
    - 'db/migrate/**/*'

Style/Documentation:
  # Don't require documentation comments for every class
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'db/migrate/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Rails cops
Rails/ApplicationRecord:
  Enabled: true

Rails/ApplicationJob:
  Enabled: true

Rails/ApplicationController:
  Enabled: true

Rails/InverseOf:
  Enabled: false  # Can be overly strict

Rails/HasManyOrHasOneDependent:
  Enabled: false  # We'll add dependent options where needed, but not enforce it globally

Rails/UniqueValidationWithoutIndex:
  Enabled: false  # Migration exists but needs to be run: 20251103022801_add_unique_index_to_user_games_user_id_and_game_id.rb

Rails/TimeZone:
  EnforcedStyle: strict

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - production

# RSpec cops
RSpec/ExampleLength:
  Max: 35  # Some integration tests need more lines for data assertions
  Exclude:
    - 'spec/requests/**/*'  # Request specs often have longer examples for full response validation

RSpec/MultipleExpectations:
  Max: 9  # Some tests verify multiple related things

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/system/**/*'
    - 'spec/schema/**/*'  # GraphQL schema specs use string descriptions

RSpec/MultipleMemoizedHelpers:
  Max: 6  # Some complex specs need more helpers

RSpec/EmptyLineAfterSubject:
  Enabled: false

RSpec/ContextWording:
  Enabled: false  # Context descriptions are descriptive enough without requiring specific prefixes

RSpec/InstanceVariable:
  Enabled: false  # Instance variables are acceptable in RSpec for @auth_headers and similar

# Bundler cops
Bundler/OrderedGems:
  Enabled: false

Bundler/DuplicatedGem:
  Enabled: true

# Metrics cops
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
    - 'Rakefile'
    - 'Guardfile'
    - 'app/admin/**/*'  # ActiveAdmin blocks can be long

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 30
  Exclude:
    - 'db/migrate/**/*'
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'db/migrate/**/*'
    - 'app/controllers/api/v1/characters_controller.rb'  # update method handles complex parameter logic
    - 'app/controllers/application_controller.rb'  # parse_auth_token handles JWT parsing
    - 'app/models/character.rb'  # max_spells_prepared has complex formula parsing
    - 'app/services/character_service.rb'  # validate_proficiencies parses complex skill descriptions
    - 'app/models/spell_list_item.rb'  # validation logic is inherently complex

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'db/migrate/**/*'
    - 'app/services/character_service.rb'  # validate_proficiencies has many conditional branches

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'db/migrate/**/*'
    - 'app/models/concerns/archetypes/archetype.rb'  # spell_slots_at_level handles multiple casting types
    - 'app/services/character_service.rb'  # Complex validation and rule application logic

# Naming cops
Naming/VariableNumber:
  EnforcedStyle: snake_case
  Exclude:
    - 'config/routes.rb'  # API version numbers like :v1 are acceptable

# Lint cops
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'

Lint/MissingSuper:
  Enabled: false  # Archetype subclasses intentionally don't call super in initialize

# Security cops
Security/YAMLLoad:
  Enabled: true

Security/JSONLoad:
  Enabled: true