name: Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
        with:
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rails db:{create,migrate}
      - run: bundle exec rspec
        env:
          COVERAGE: true
          RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}
